version: "3.8"
name: ai-gallery
services:
  django:
    container_name: django
    env_file:
      - .env-prod
    build:
      context: .
      dockerfile: Dockerfile
    image: django
    ports:
      - "8002:8000"
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - django
