version: "3.8"
services:
  django:
    container_name: ai-gallery-dev
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - django
